python train.py --device cpu --model_type LSTM --input_length 5
python train.py --device cpu --model_type LSTM --input_length 6
python train.py --device cpu --model_type LSTM --input_length 7
python train.py --device cpu --model_type LSTM --input_length 8
python train.py --device cpu --model_type LSTM --input_length 9
python train.py --device cpu --model_type LSTM --input_length 10
python train.py --device cpu --model_type LSTM --input_length 11
python train.py --device cpu --model_type LSTM --input_length 12
python train.py --device cpu --model_type LSTM --input_length 13
python train.py --device cpu --model_type LSTM --input_length 14
python train.py --device cpu --model_type LSTM --input_length 15
python train.py --device cpu --model_type LSTM --input_length 16
python train.py --device cpu --model_type LSTM --input_length 17
python train.py --device cpu --model_type LSTM --input_length 18
python train.py --device cpu --model_type LSTM --input_length 19
python train.py --device cpu --model_type LSTM --input_length 20
python train.py --device cpu --model_type LSTM --input_length 21
python train.py --device cpu --model_type LSTM --input_length 22
python train.py --device cpu --model_type LSTM --input_length 23
python train.py --device cpu --model_type LSTM --input_length 24
python train.py --device cpu --model_type LSTM --input_length 25
python train.py --device cpu --model_type LSTM --input_length 26
python train.py --device cpu --model_type LSTM --input_length 27
python train.py --device cpu --model_type LSTM --input_length 28
python train.py --device cpu --model_type LSTM --input_length 29
python train.py --device cpu --model_type LSTM --input_length 30
python train.py --device cpu --model_type LSTM --input_length 31
python train.py --device cpu --model_type LSTM --input_length 32
python train.py --device cpu --model_type LSTM --input_length 33
python train.py --device cpu --model_type LSTM --input_length 34
python train.py --device cpu --model_type LSTM --input_length 35
